name: Deploy Homepage

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set ssh key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan "$SSH_HOST" >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/ssh.key
          chmod 600 ~/.ssh/ssh.key
          cat >> ~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ssh.key
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: deploy
        run: |
          ssh server "
            cd ~/apps/mcxue-ui
            git checkout $COMMIT_REF_NAME
            if output=\$(git pull); then
              if [[ \"\$output\" == *\"Already up-to-date.\"* ]]; then
                echo \"仓库代码已是最新的，无需更新\"
              else
                echo \"拉取最新代码并部署：\$(git log -1 --oneline)\"
                docker compose up --build -d
              fi
            else
              echo \"git pull 命令执行失败，退出状态码为 \$?\"
            fi
          "
          echo "结束"
        env:
          COMMIT_REF_NAME: ${{ github.ref_name }}
      - name: remove ssh key
        run: rm -rf ~/.ssh
